services:
  cloudflared:
    image: cloudflare/cloudflared:2025.2.1
    command: tunnel --no-autoupdate run
    env_file: .env
    depends_on:
      dev:
        condition: service_healthy
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:rw,z
    working_dir: /app
    entrypoint: npm
    command: run dev -- --host
    environment:
      ALLOW_ANY_HOST: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
